# Generated by Django 4.0.4 on 2023-01-08 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_name', models.CharField(max_length=15, verbose_name='Фамилия')),
                ('f_name', models.CharField(max_length=15, verbose_name='Имя')),
                ('p_name', models.CharField(max_length=15, verbose_name='Отчество')),
                ('age', models.PositiveIntegerField(default=20, verbose_name='Возраст')),
                ('experience', models.FloatField(default=0, verbose_name='Стаж')),
                ('other_data', models.TextField(blank=True, default='нет', verbose_name='Другие данные')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='Название компании')),
                ('address', models.CharField(max_length=60, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, default='Не указан', max_length=11, null=True, verbose_name='Номер телефона')),
                ('other_contact_information', models.CharField(blank=True, default='Не указано', max_length=70, verbose_name='Другие контактные данные')),
            ],
        ),
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_name', models.CharField(max_length=40, verbose_name='Название профессии')),
            ],
        ),
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_name', models.CharField(max_length=40, verbose_name='Название квалификации')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=40, verbose_name='Название навыка')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tob_name', models.CharField(max_length=40, verbose_name='Название вида деятельности')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_about', models.TextField(blank=True, default='', verbose_name='Описание вакансии')),
                ('salary', models.PositiveIntegerField(verbose_name='Зарплата')),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.employer', verbose_name='Работодатель')),
                ('minimum_qualification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.qualifications', verbose_name='Минимальная допустимая квалификация')),
                ('profession_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.professions', verbose_name='Профессия')),
            ],
        ),
        migrations.CreateModel(
            name='UserAndHisType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_user', models.CharField(choices=[('APL', 'Соискатель'), ('EMP', 'Работодатель'), ('MDR', 'Модератор')], default='APL', max_length=3, verbose_name='Тип пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='employer',
            name='type_of_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.typeofbusiness', verbose_name='Вид деятельности'),
        ),
        migrations.AddField(
            model_name='employer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.applicant', verbose_name='Соискатель')),
                ('profession_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.professions', verbose_name='Профессия')),
                ('qualification_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.qualifications', verbose_name='Квалификация')),
            ],
        ),
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comission', models.IntegerField(verbose_name='Комиссионные')),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.applicant', verbose_name='Соискатель')),
                ('vacancy_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.vacancy', verbose_name='Вакансия')),
            ],
        ),
    ]
